### PR TITLE
Prevent panics in NamespacedHash.set_hash

### LINKED ISSUE #9: Prevent panics in `NamespacedHash.set_hash`
Currently `NamespacedHash.set_hash` accepts a `&[u8]` and uses `copy_from_slice` internally. To avoid panics, it should either require a `&[u8; NAMESPACED_HASH_LEN]` or return a `Result` with an appropriate error if the slice has the wrong length.

### PR DESCRIPTION
**Pull request by preston-evans98**
Statically check the arguments to NamespacedHash.set_hash to avoid panics. Closes #9

### CODE REVIEW

**Review by bkolad — APPROVED** [review]

File: src/namespaced_hash.rs [hunk 1]
```diff
@@ -295,7 +295,7 @@ impl<const NS_ID_SIZE: usize> NamespacedHash<NS_ID_SIZE> {
         self.hash
     }
 
-    fn set_hash(&mut self, new_hash: &[u8]) {
+    fn set_hash(&mut self, new_hash: &[u8; HASH_LEN]) {
```
Comment (vlopes11) [inline src/namespaced_hash.rs:298]: A reference to an array is more restrictive than a reference to a slice. Meaning: any array can be represented as slice for free, but the other way around will not be possible without copy and/or unsafe code.

One example to consider is blobs of well-structured bytes that will often be represented as `Vec<u8>`, or even `[u8; N]`, where we know to contain a slice that will represent the hash input.

For such case, we will be forced to copy the slice to an array, and then pass as reference.

Prior to the fix, the function extends the property of `copy_from_slice`, that will [panic](https://doc.rust-lang.org/std/primitive.slice.html#panics-29) if the length is not the same. Considering this function is of private scope, we can be more tolerant to panics.

One alternative to consider is to create a `fn set_hash_checked` that will perform such assertion.

Comment (preston-evans98) [reply src/namespaced_hash.rs:298]: > A reference to an array is more restrictive than a reference to a slice. 
Yep, that's the point - we want type safety here to avoid accidental misuse. Since this function is private, and the modified code compiles, we know we don't need the more permissive variant in cases where this is used. (There are appropriate options for creating hashes from the public API)
